FROM node:20.12-slim

WORKDIR /app
COPY ./skyvern-frontend /app
COPY ./entrypoint-skyvernui.sh /app/entrypoint-skyvernui.sh
RUN npm install

ENV VITE_API_BASE_URL=http://10.161.159.131:8000/api/v1
ENV VITE_ARTIFACT_API_BASE_URL=http://10.161.159.131:9090

CMD [ "/bin/bash", "/app/entrypoint-skyvernui.sh" ]

